### PR TITLE
Cookbook Refactors

### PR DESCRIPTION
**Pull request by awatson1978**
Various refactors and edits.  Lots of small edits that leverage server side publications, client-side searches, date range searches, and the like.  Anyhow, be aware that it's possible to do case-insensitive $regex searches with the 'i' option, like so:  

`name: {$regex: Session.get('nameFilter'),$options: 'i'}`

Anyhow, you may want to do a `git pull https://github.com/awatson1978/meteor-query-test` and test things out before merging branches.

### CODE REVIEW

**Comment by chafey** [comment]
If I am reading this change correctly, you got rid of server side filtering and it is now all done on the client?  This won't work if there are millions of patient records...?

**Comment by awatson1978** [comment]
Yes and no.  It's not all done on the client.  But it definitely leverages the client side cursor.  

You know how PACS workstations are often built as mini database servers?  There's an SQL database running on the localhost, which synchronizes with the PACS Archive in the datacenter?  The Radiologist's viewer connects to the local SQL database instead of the PACS archive, even though the 'sql database server' is just running on the local workstation.

That's how this is written.  Minimongo is acting as the client-side data store, just like that local SQL database instance.  Mongo is acting like the PACS Archive in the datacenter.  

It might help to think of it as prefetch rules.  The publications are now acting like a prefetch mechanism.

**Comment by awatson1978** [comment]
And, of course, you have to decide how to write your prefetch rules, and avoid prefetching a million records.

**Comment by chafey** [comment]
OK I see the disconnect - the use case I was targeting here is doing an ad hoc query for a patient in the main archive which could have millions of patients in it.  Can we keep this specific example focused on that use case?

**Comment by awatson1978** [comment]
No problem.  The merge conflict makes it difficult to merge anyhow.  I'll rename my repository to patient-prefetch-lookup.  Nonetheless, there are some patterns in this new version that are worth taking note of.  Being able to do case insensitive searches, how to do date queries using native Date() objects and not needing a datestamp (I think you'll find that the example provided handles time zones correctly), etc.

**Comment by chafey** [comment]
OK sounds good - I'll refactor this project to better align with the changes you made.  We can refactor any common/shared/general functionality into another package when it makes sense.

**Comment by awatson1978** [comment]
Also, I've been giving some thought to the idea of Patient and Physician collections, and keep coming back to the following questions:  What if there is a need to provide a patient portal?  Patients would then need user accounts, right?  What if Physicians need to use the system as patients?  Again, they'd need need user accounts.  

Keeping all user accounts in the Meteor.users collection seems like the way to go.  At least as far as the tests I've done go.  A roles field allows for the collection to produce a Physicians cursor or Patients cursor as needed.  And roles should index nicely, I think, and have good performance.  It might not be relevant for this example, but it's the direction I'm leaning towards with my other apps.

$0.02

**Comment by awatson1978** [comment]
Anyhow, closing since review is done.

**Pull request closed without merging**
